#apiVersion: apps/v1 #mj - changed apps/v1beta to v1
apiVersion: apps/v1beta #mj - changed apps/v1beta to v1
kind: Deployment
metadata:
  name: fortio
# spec:
#   selector: #mandatory field
#       matchLabels: #mandatory field
#         app: fortio #mandatory field
  progressDeadlineSeconds: 500
  replicas: 1
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:latest_release
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping
